### ISSUE TITLE
RabbitMQ file name limit

### ISSUE THREAD

**Issue by mmattos-newrelic** [newrelic/infrastructure-bundle#355]
### Description
After updating the integration to the new infrastructure bundle, the integration started to generate errors for very long file names.

### Acceptance Criteria
increase the limit size of RabbitMQ queue file names

### Describe Alternatives
N/A

### Dependencies
I don't think so, as it should just be a direct adjustment to the integration's source code.

### Additional context
Documentation consulted during the upgrade process and problem detection.
old: https://hub.docker.com/r/newrelic/k8s-nri-rabbitmq
new: https://hub.docker.com/r/newrelic/infrastructure-bundle
git update: https://github.com/newrelic/nri-rabbitmq/commit/6ad81341ed404925141bd820b2f8999840b79e81
forum: https://forum.newrelic.com/s/hubtopic/aAX8W0000008advWAA/rabbitmq-monitoring-doesnt-work-for-queuesregexes-

Log file collected during the troubleshooting:
[log_queues.txt](https://github.com/newrelic/infrastructure-bundle/files/13639505/log_queues.txt)

### Estimates
L = 1-2 weeks

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by paologallinaharbur** [comment]
It seems related to the way the infra-agent is processing inventory. Could you try switching off inventory collection?

To do so, you can add in the integration config:
```
METRIC="true" 
INVENTORY="false"
```

This will configure the integration to avoid collecting the inventory and therefore "solving" that issue.
The real solution would be understanding why that name is so long that we cannot store it, but I imagine it is due to some queues names that are very long and the fact that we need to concatenate different into to make sure entity names do not collide 😕

**Comment by mmattos-newrelic** [comment]
Thanks for the tip, Paolo.

I’ll test this configuration with the customer and report the results as soon as possible.

Cheers!

Miguel Mattos
Senior Solution Consultant
+55.11.9.4203-4744
***@***.*** ***@***.***>


￼

**Comment by paologallinaharbur** [comment]
I've just realized it is an internal request, could you open on their behalf a GTS and if needed they can escalate it with a GTSE?

**Comment by mmattos-newrelic** [comment]
Ok, Paolo.

Customer is already testing your suggestion. I’ll open a GTS ticket case we can't solve it, ok?

Miguel Mattos
Senior Solution Consultant
+55.11.9.4203-4744
***@***.*** ***@***.***>


￼
